name: API Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "1 23 * * 1"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      env:
        GOCRONOMETER_TEST_USERNAME: ${{ secrets.GOCRONOMETER_TEST_USERNAME }}
        GOCRONOMETER_TEST_PASSWORD: ${{ secrets.GOCRONOMETER_TEST_PASSWORD }}
      run: go test -v -run TestClient_ExportExercises

